<?php
if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}
?>
<?php
$this->headTitle($this->title);
$form = $this->form;
$form->prepare();
$form->setAttribute('action', '/login');
$form->get('username')->setAttribute('class', 'textbox');
$form->get('password')->setAttribute('class', 'textbox');
$form->get('submit')->setAttribute('class', 'button');
?>

<?php echo $this->form()->openTag($form); ?>
<div class="label">
USERNAME<span class="red">*</span>
</div>
<div class="textbox-div">
<?php echo $this->formText($form->get('username')); ?>
<?php echo $this->formElementerrors($form->get('username')); ?>
</div>
<div class="label">
PASSWORD<span class="red">*</span>
</div>
<div class="textbox-div">
<?php echo $this->formPassword($form->get('password')); ?>
<?php echo $this->formElementerrors($form->get('password')); ?>
</div>
<div class="textbox-div">
<?php echo $this->formElement($form->get('csrf')) ?>
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
<br />
